# Generated by Django 5.2.17 on 2026-08-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='codigo',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='especialidades/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='profesion',
            field=models.CharField(default='', help_text='Nombre de la profesión, por ejemplo: Cardiólogo, Pediatra, Radiólogo, etc.', max_length=60, unique=True, verbose_name='Profesión'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(help_text='Nombre de la disciplina, por ejemplo: Cardiología, Pediatría, Radiología, etc.', max_length=60, unique=True, verbose_name='Especialidad'),
        ),
    ]
