# Generated by Django 5.2.17 on 2026-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='documento_numero',
            field=models.CharField(max_length=12, verbose_name='Documento número'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documento_tipo',
            field=models.CharField(choices=[('dni', 'DNI'), ('nie', 'NIE'), ('pass', 'Pasaporte'), ('otro', 'Otro')], max_length=4, verbose_name='Documento tipo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nhc',
            field=models.CharField(help_text='número de historia clínica', max_length=20, verbose_name='NHC'),
        ),
    ]
