# Generated by Django 5.2.17 on 2026-08-28 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0002_remove_especialidad_codigo_especialidad_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('colegiado', models.CharField(max_length=12, verbose_name='n.º de colegiado')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizacion.grupo', verbose_name='grupo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medico', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'médico',
                'verbose_name_plural': 'médicos',
                'db_table': 'medi_medicos',
                'ordering': ['grupo', 'usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicoClinicaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos_asignados', to='organizacion.clinica', verbose_name='clínica')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_medico', to='organizacion.especialidad', verbose_name='especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_clinica', to='medicos.medico', verbose_name='médico')),
            ],
            options={
                'verbose_name': 'especialidad de médico por clínica',
                'verbose_name_plural': 'especialidades de médico por clínica',
                'db_table': 'medi_medico_clinica_especialidades',
                'ordering': ['medico', 'clinica'],
            },
        ),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('grupo', 'colegiado'), name='medi_medico_unique_grupo_colegiado'),
        ),
        migrations.AddConstraint(
            model_name='medicoclinicaespecialidad',
            constraint=models.UniqueConstraint(fields=('medico', 'clinica'), name='medi_medicoclinicaespecialidad_unique_medico_clinica'),
        ),
    ]
