# Generated by Django 5.2.17 on 2026-09-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('motivo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('baja', 'Baja médica'), ('congreso', 'Congreso'), ('bloqueo_manual', 'Bloqueo manual'), ('otro', 'Otro')], max_length=30, verbose_name='motivo')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=1, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'ausencia',
                'verbose_name_plural': 'ausencias',
                'db_table': 'medi_ausencias',
                'ordering': ['medico', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MedicoClinicaEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'especialidad de médico por clínica',
                'verbose_name_plural': 'especialidades de médico por clínica',
                'db_table': 'medi_medico_clinica_especialidades',
                'ordering': ['medico', 'clinica'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('colegiado', models.CharField(max_length=12, verbose_name='n.º de colegiado')),
                ('tratamiento', models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Dra', 'Dra')], help_text='tratamiento formal del médico (Dr./Dra.)', max_length=3, null=True, verbose_name='tratamiento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organizacion.grupo', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'médico',
                'verbose_name_plural': 'médicos',
                'db_table': 'medi_medicos',
                'ordering': ['grupo', 'usuario__last_name', 'usuario__first_name'],
            },
        ),
    ]
