# Generated by Django 5.2.17 on 2026-09-04 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medico', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='medicoausencia',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='medicos.medico', verbose_name='médico'),
        ),
        migrations.AddField(
            model_name='medicoclinicaespecialidad',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos_asignados', to='organizacion.clinica', verbose_name='clínica'),
        ),
        migrations.AddField(
            model_name='medicoclinicaespecialidad',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_medico', to='organizacion.especialidad', verbose_name='especialidad'),
        ),
        migrations.AddField(
            model_name='medicoclinicaespecialidad',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_clinica', to='medicos.medico', verbose_name='médico'),
        ),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('grupo', 'colegiado'), name='medi_medico_unique_grupo_colegiado'),
        ),
        migrations.AddConstraint(
            model_name='medicoausencia',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='medi_ausencia_fecha_fin_gte_fecha_inicio'),
        ),
        migrations.AddConstraint(
            model_name='medicoclinicaespecialidad',
            constraint=models.UniqueConstraint(fields=('medico', 'clinica'), name='medi_medicoclinicaespecialidad_unique_medico_clinica'),
        ),
    ]
