# Generated by Django 5.2.17 on 2026-09-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('motivo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('baja', 'Baja médica'), ('congreso', 'Congreso'), ('bloqueo_manual', 'Bloqueo manual'), ('otro', 'Otro')], max_length=30, verbose_name='motivo')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada')], default='P', max_length=1, verbose_name='estado')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='medicos.medico', verbose_name='médico')),
            ],
            options={
                'verbose_name': 'ausencia',
                'verbose_name_plural': 'ausencias',
                'db_table': 'medi_ausencias',
                'ordering': ['medico', 'fecha_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='medi_ausencia_fecha_fin_gte_fecha_inicio')],
            },
        ),
    ]
