# Generated by Django 5.2.17 on 2026-08-25 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_remove_especialidad_codigo_especialidad_imagen_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='organizacion.grupo', verbose_name='grupo'),
        ),
        migrations.CreateModel(
            name='UsuarioClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('rol', models.CharField(choices=[('SUPERADMIN', 'Superadministrador'), ('GROUP_ADMIN', 'Administrador de grupo'), ('CLINIC_ADMIN', 'Administrador de clínica'), ('DOCTOR', 'Médico'), ('RECEPTIONIST', 'Recepción')], max_length=20, verbose_name='rol')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_asignados', to='organizacion.clinica', verbose_name='clínica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'asignación de usuario a clínica',
                'verbose_name_plural': 'asignaciones de usuario a clínica',
                'db_table': 'usua_usuario_clinicas',
                'ordering': ['usuario', 'clinica'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'clinica'), name='usua_usuarioclinica_unique_usuario_clinica')],
            },
        ),
    ]
