# Generated by Django 5.2.17 on 2026-08-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_grupo_usuarioclinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
